--
-- PostgreSQL database dump
--

\restrict 3MUgoRJBNXu9MWeGMmhUgjvo0Aswy42F4Y5lmvGJmcs6nAmHK0FvcEVGCpHdfI8

-- Dumped from database version 13.23
-- Dumped by pg_dump version 13.23

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: accounts; Type: TABLE; Schema: public; Owner: orion_admin
--

CREATE TABLE public.accounts (
    id uuid NOT NULL,
    type character varying(50) NOT NULL,
    name character varying(255) NOT NULL,
    external_id character varying(255) DEFAULT NULL::character varying,
    credentials json NOT NULL,
    status character varying(20) NOT NULL,
    settings json,
    created_at timestamp(0) without time zone NOT NULL,
    updated_at timestamp(0) without time zone NOT NULL,
    user_id uuid NOT NULL
);


ALTER TABLE public.accounts OWNER TO orion_admin;

--
-- Name: attachments; Type: TABLE; Schema: public; Owner: orion_admin
--

CREATE TABLE public.attachments (
    id uuid NOT NULL,
    type character varying(20) NOT NULL,
    file_name character varying(255) NOT NULL,
    file_size integer NOT NULL,
    mime_type character varying(100) NOT NULL,
    url character varying(255) NOT NULL,
    external_id character varying(255) DEFAULT NULL::character varying,
    created_at timestamp(0) without time zone NOT NULL,
    message_id uuid NOT NULL
);


ALTER TABLE public.attachments OWNER TO orion_admin;

--
-- Name: contacts; Type: TABLE; Schema: public; Owner: orion_admin
--

CREATE TABLE public.contacts (
    id uuid NOT NULL,
    main_name character varying(255) NOT NULL,
    first_name character varying(255) DEFAULT NULL::character varying,
    last_name character varying(255) DEFAULT NULL::character varying,
    avatar_url character varying(255) DEFAULT NULL::character varying,
    metadata json,
    created_at timestamp(0) without time zone NOT NULL,
    updated_at timestamp(0) without time zone NOT NULL
);


ALTER TABLE public.contacts OWNER TO orion_admin;

--
-- Name: conversations; Type: TABLE; Schema: public; Owner: orion_admin
--

CREATE TABLE public.conversations (
    id uuid NOT NULL,
    external_id character varying(255),
    type character varying(50) NOT NULL,
    status character varying(50) NOT NULL,
    last_message_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone NOT NULL,
    unread_count integer NOT NULL,
    created_at timestamp(0) without time zone NOT NULL,
    updated_at timestamp(0) without time zone NOT NULL,
    account_id uuid NOT NULL,
    contact_id uuid,
    assigned_to_id uuid,
    target_user_id uuid
);


ALTER TABLE public.conversations OWNER TO orion_admin;

--
-- Name: doctrine_migration_versions; Type: TABLE; Schema: public; Owner: orion_admin
--

CREATE TABLE public.doctrine_migration_versions (
    version character varying(191) NOT NULL,
    executed_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    execution_time integer
);


ALTER TABLE public.doctrine_migration_versions OWNER TO orion_admin;

--
-- Name: messages; Type: TABLE; Schema: public; Owner: orion_admin
--

CREATE TABLE public.messages (
    id uuid NOT NULL,
    sender_type character varying(20) NOT NULL,
    sender_id uuid,
    external_id character varying(255) DEFAULT NULL::character varying,
    text text,
    payload json,
    is_read boolean NOT NULL,
    direction character varying(20) NOT NULL,
    sent_at timestamp(0) without time zone NOT NULL,
    created_at timestamp(0) without time zone NOT NULL,
    conversation_id uuid NOT NULL,
    status character varying(20) DEFAULT 'sent'::character varying NOT NULL
);


ALTER TABLE public.messages OWNER TO orion_admin;

--
-- Name: messenger_messages; Type: TABLE; Schema: public; Owner: orion_admin
--

CREATE TABLE public.messenger_messages (
    id bigint NOT NULL,
    body text NOT NULL,
    headers text NOT NULL,
    queue_name character varying(190) NOT NULL,
    created_at timestamp(0) without time zone NOT NULL,
    available_at timestamp(0) without time zone NOT NULL,
    delivered_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone
);


ALTER TABLE public.messenger_messages OWNER TO orion_admin;

--
-- Name: messenger_messages_id_seq; Type: SEQUENCE; Schema: public; Owner: orion_admin
--

ALTER TABLE public.messenger_messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.messenger_messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: orion_admin
--

CREATE TABLE public.users (
    id uuid NOT NULL,
    email character varying(180) NOT NULL,
    roles json NOT NULL,
    password character varying(255) NOT NULL,
    first_name character varying(100) DEFAULT NULL::character varying NOT NULL,
    last_name character varying(100) DEFAULT NULL::character varying NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp(0) without time zone NOT NULL,
    updated_at timestamp(0) without time zone NOT NULL
);


ALTER TABLE public.users OWNER TO orion_admin;

--
-- Data for Name: accounts; Type: TABLE DATA; Schema: public; Owner: orion_admin
--

COPY public.accounts (id, type, name, external_id, credentials, status, settings, created_at, updated_at, user_id) FROM stdin;
\.


--
-- Data for Name: attachments; Type: TABLE DATA; Schema: public; Owner: orion_admin
--

COPY public.attachments (id, type, file_name, file_size, mime_type, url, external_id, created_at, message_id) FROM stdin;
\.


--
-- Data for Name: contacts; Type: TABLE DATA; Schema: public; Owner: orion_admin
--

COPY public.contacts (id, main_name, first_name, last_name, avatar_url, metadata, created_at, updated_at) FROM stdin;
\.


--
-- Data for Name: conversations; Type: TABLE DATA; Schema: public; Owner: orion_admin
--

COPY public.conversations (id, external_id, type, status, last_message_at, unread_count, created_at, updated_at, account_id, contact_id, assigned_to_id, target_user_id) FROM stdin;
\.


--
-- Data for Name: doctrine_migration_versions; Type: TABLE DATA; Schema: public; Owner: orion_admin
--

COPY public.doctrine_migration_versions (version, executed_at, execution_time) FROM stdin;
DoctrineMigrations\\Version20260203232207	2026-02-06 18:18:17	79
DoctrineMigrations\\Version20260204121410	2026-02-06 18:18:17	6
DoctrineMigrations\\Version20260205165003	2026-02-06 18:35:49	12
DoctrineMigrations\\Version20260205202926	2026-02-06 18:35:49	34
\.


--
-- Data for Name: messages; Type: TABLE DATA; Schema: public; Owner: orion_admin
--

COPY public.messages (id, sender_type, sender_id, external_id, text, payload, is_read, direction, sent_at, created_at, conversation_id, status) FROM stdin;
\.


--
-- Data for Name: messenger_messages; Type: TABLE DATA; Schema: public; Owner: orion_admin
--

COPY public.messenger_messages (id, body, headers, queue_name, created_at, available_at, delivered_at) FROM stdin;
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: orion_admin
--

COPY public.users (id, email, roles, password, first_name, last_name, is_active, created_at, updated_at) FROM stdin;
81cb42a7-31eb-46a5-bd14-e26c9e01711e	a@a.ru	["ROLE_ADMIN","ROLE_USER"]	$2y$13$x4eekHjC1MDVCeQ3qlzCJeCDfHeCDaMYrRrDsXY9l2kabXvWV.DgS	Admin	Orion	t	2026-02-06 19:35:40	2026-02-06 19:35:40
70b7f809-8b43-4979-b304-9976254fa438	yur1980@mail.ru	["ROLE_ADMIN","ROLE_USER"]	$2y$13$VC/H.VnJNBLgb4/TwoRe2.bjpbLGKFbUjATq66j5.S.nn1NrYkT9K	Юрий	Перцев	t	2026-02-06 19:48:57	2026-02-06 19:48:57
\.


--
-- Name: messenger_messages_id_seq; Type: SEQUENCE SET; Schema: public; Owner: orion_admin
--

SELECT pg_catalog.setval('public.messenger_messages_id_seq', 1, false);


--
-- Name: accounts accounts_pkey; Type: CONSTRAINT; Schema: public; Owner: orion_admin
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT accounts_pkey PRIMARY KEY (id);


--
-- Name: attachments attachments_pkey; Type: CONSTRAINT; Schema: public; Owner: orion_admin
--

ALTER TABLE ONLY public.attachments
    ADD CONSTRAINT attachments_pkey PRIMARY KEY (id);


--
-- Name: contacts contacts_pkey; Type: CONSTRAINT; Schema: public; Owner: orion_admin
--

ALTER TABLE ONLY public.contacts
    ADD CONSTRAINT contacts_pkey PRIMARY KEY (id);


--
-- Name: conversations conversations_pkey; Type: CONSTRAINT; Schema: public; Owner: orion_admin
--

ALTER TABLE ONLY public.conversations
    ADD CONSTRAINT conversations_pkey PRIMARY KEY (id);


--
-- Name: doctrine_migration_versions doctrine_migration_versions_pkey; Type: CONSTRAINT; Schema: public; Owner: orion_admin
--

ALTER TABLE ONLY public.doctrine_migration_versions
    ADD CONSTRAINT doctrine_migration_versions_pkey PRIMARY KEY (version);


--
-- Name: messages messages_pkey; Type: CONSTRAINT; Schema: public; Owner: orion_admin
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT messages_pkey PRIMARY KEY (id);


--
-- Name: messenger_messages messenger_messages_pkey; Type: CONSTRAINT; Schema: public; Owner: orion_admin
--

ALTER TABLE ONLY public.messenger_messages
    ADD CONSTRAINT messenger_messages_pkey PRIMARY KEY (id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: orion_admin
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: idx_47c4fad6537a1329; Type: INDEX; Schema: public; Owner: orion_admin
--

CREATE INDEX idx_47c4fad6537a1329 ON public.attachments USING btree (message_id);


--
-- Name: idx_75ea56e0fb7336f0e3bd61ce16ba31dbbf396750; Type: INDEX; Schema: public; Owner: orion_admin
--

CREATE INDEX idx_75ea56e0fb7336f0e3bd61ce16ba31dbbf396750 ON public.messenger_messages USING btree (queue_name, available_at, delivered_at, id);


--
-- Name: idx_c2521bf16c066afe; Type: INDEX; Schema: public; Owner: orion_admin
--

CREATE INDEX idx_c2521bf16c066afe ON public.conversations USING btree (target_user_id);


--
-- Name: idx_c2521bf19b6b5fba; Type: INDEX; Schema: public; Owner: orion_admin
--

CREATE INDEX idx_c2521bf19b6b5fba ON public.conversations USING btree (account_id);


--
-- Name: idx_c2521bf1e7a1254a; Type: INDEX; Schema: public; Owner: orion_admin
--

CREATE INDEX idx_c2521bf1e7a1254a ON public.conversations USING btree (contact_id);


--
-- Name: idx_c2521bf1f4bd7827; Type: INDEX; Schema: public; Owner: orion_admin
--

CREATE INDEX idx_c2521bf1f4bd7827 ON public.conversations USING btree (assigned_to_id);


--
-- Name: idx_cac89eaca76ed395; Type: INDEX; Schema: public; Owner: orion_admin
--

CREATE INDEX idx_cac89eaca76ed395 ON public.accounts USING btree (user_id);


--
-- Name: idx_db021e969ac0396; Type: INDEX; Schema: public; Owner: orion_admin
--

CREATE INDEX idx_db021e969ac0396 ON public.messages USING btree (conversation_id);


--
-- Name: uniq_1483a5e9e7927c74; Type: INDEX; Schema: public; Owner: orion_admin
--

CREATE UNIQUE INDEX uniq_1483a5e9e7927c74 ON public.users USING btree (email);


--
-- Name: attachments fk_47c4fad6537a1329; Type: FK CONSTRAINT; Schema: public; Owner: orion_admin
--

ALTER TABLE ONLY public.attachments
    ADD CONSTRAINT fk_47c4fad6537a1329 FOREIGN KEY (message_id) REFERENCES public.messages(id) ON DELETE CASCADE;


--
-- Name: conversations fk_c2521bf16c066afe; Type: FK CONSTRAINT; Schema: public; Owner: orion_admin
--

ALTER TABLE ONLY public.conversations
    ADD CONSTRAINT fk_c2521bf16c066afe FOREIGN KEY (target_user_id) REFERENCES public.users(id);


--
-- Name: conversations fk_c2521bf19b6b5fba; Type: FK CONSTRAINT; Schema: public; Owner: orion_admin
--

ALTER TABLE ONLY public.conversations
    ADD CONSTRAINT fk_c2521bf19b6b5fba FOREIGN KEY (account_id) REFERENCES public.accounts(id);


--
-- Name: conversations fk_c2521bf1e7a1254a; Type: FK CONSTRAINT; Schema: public; Owner: orion_admin
--

ALTER TABLE ONLY public.conversations
    ADD CONSTRAINT fk_c2521bf1e7a1254a FOREIGN KEY (contact_id) REFERENCES public.contacts(id);


--
-- Name: conversations fk_c2521bf1f4bd7827; Type: FK CONSTRAINT; Schema: public; Owner: orion_admin
--

ALTER TABLE ONLY public.conversations
    ADD CONSTRAINT fk_c2521bf1f4bd7827 FOREIGN KEY (assigned_to_id) REFERENCES public.users(id);


--
-- Name: accounts fk_cac89eaca76ed395; Type: FK CONSTRAINT; Schema: public; Owner: orion_admin
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT fk_cac89eaca76ed395 FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: messages fk_db021e969ac0396; Type: FK CONSTRAINT; Schema: public; Owner: orion_admin
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT fk_db021e969ac0396 FOREIGN KEY (conversation_id) REFERENCES public.conversations(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict 3MUgoRJBNXu9MWeGMmhUgjvo0Aswy42F4Y5lmvGJmcs6nAmHK0FvcEVGCpHdfI8

